class FieldRegistry:
  FIELDS = {
    'A':  { 'human': 'seller_vat_number'           , 'type': 's' },
    'B':  { 'human': 'buyer_vat_number'            , 'type': 's' },
    'C':  { 'human': 'buyer_country'               , 'type': 's' },
    'D':  { 'human': 'document_type'               , 'type': 's' },
    'E':  { 'human': 'document_status'             , 'type': 's' },
    'F':  { 'human': 'document_date'               , 'type': 'd' },
    'G':  { 'human': 'document_id'                 , 'type': 's' },
    'H':  { 'human': 'atcud'                       , 'type': 's' },
    'L':  { 'human': 'total_vat_exempt'            , 'type': 'c' },
    'M':  { 'human': 'total_stamp_duty'            , 'type': 'c' },
    'N':  { 'human': 'total_vat'                   , 'type': 'c' },
    'O':  { 'human': 'total_gross'                 , 'type': 'c' },
    'P':  { 'human': 'total_tax_witholded'         , 'type': 'c' },
    'Q':  { 'human': 'hash'                        , 'type': 's' },
    'R':  { 'human': 'software_certificate'        , 'type': 's' },
    'S':  { 'human': 'other_info'                  , 'type': 'a' },
    'I1': {                                          'type': 's' },
    'I2': {                                          'type': 's' },
    'I3': {                                          'type': 's' },
    'I4': {                                          'type': 's' },
    'I5': {                                          'type': 's' },
    'I6': {                                          'type': 's' },
    'I7': {                                          'type': 's' },
    'I8': {                                          'type': 's' },
    'J1': {                                          'type': 's' },
    'J2': {                                          'type': 's' },
    'J3': {                                          'type': 's' },
    'J4': {                                          'type': 's' },
    'J5': {                                          'type': 's' },
    'J6': {                                          'type': 's' },
    'J7': {                                          'type': 's' },
    'J8': {                                          'type': 's' },
    'K1': {                                          'type': 's' },
    'K2': {                                          'type': 's' },
    'K3': {                                          'type': 's' },
    'K4': {                                          'type': 's' },
    'K5': {                                          'type': 's' },
    'K6': {                                          'type': 's' },
    'K7': {                                          'type': 's' },
    'K8': {                                          'type': 's' },
  }

  def get_field(self, name):
    return self.FIELDS[name]
